language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

 
script:
  - pytest  
  - python -m pytest --cov-report term-missing --cov=app

after_success:
  - coveralls

after_success:
  coveralls